[package]
name = "mint_session"
version = "2.0.0"
edition = "2021"

[dependencies]
casper-contract = { git = "https://github.com/casper-network/casper-node.git" }
casper-types = { git = "https://github.com/casper-network/casper-node.git" }

[[bin]]
name = "mint_call"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true
